version: "3"

dotenv: 
  - '.env'
  - '{{.ENV}}/.env'
  - '{{.HOME}}/.env'

tasks:
  format:
    cmds:
      - gofmt -w .
    silent: true
  postgres:
    cmds:
      - docker run --name postgres16 -p 5432\:5432 -e POSTGRES_USER={{.USER}} -e POSTGRES_PASSWORD={{.PASSWORD}} -d postgres\:16-alpine
    silent: true
  dockerstart:
    cmds:
      - systemctl start docker
      - docker start postgres16
  migrateup:
    cmds:
      - migrate -path db/migration/ -database "{{.DB_SOURCE}}" -verbose up

  migratedown:
    cmds:
      - migrate -path db/migration/ -database "{{.DB_SOURCE}}" -verbose down

  migrateforce:
    cmds:
      - migrate -path db/migration/ -database "{{.DB_SOURCE}}" force 1

  sqlc:
    cmds:
      - sqlc generate
    silent: true
  createdb:
    cmds:
      - docker exec -it postgres16 createdb --username={{.USER}} railway_tiket

  dropdb:
    cmds:
      - docker exec -it postgres16 dropdb --username={{.USER}} railway_tiket
