version: "3"

dotenv: 
  - '.env'
  - '{{.ENV}}/.env'
  - '{{.HOME}}/.env'

tasks:
  format:
    cmds:
      - gofmt -w .
    silent: true
  
  migrateup:
    cmds:
      - docker run --rm -v $(pwd)/db/migration:/migrations --network host migrate/migrate -path=/migrations -database "{{.DB_SOURCE}}" -verbose up 

  migratedown:
    cmds:
      - migrate -path db/migration/ -database "{{.DB_SOURCE}}" -verbose down

  migrateforce:
    cmds:
      - migrate -path db/migration/ -database "{{.DB_SOURCE}}" force 1

  sqlc:
    cmds:
      - docker run --rm -v $(pwd):/src -w /src sqlc/sqlc generate
    silent: true
  createdb:
    cmds:
      - docker exec -it postgres createdb --username={{.USER}} railway_tiket

  start:
    cmds:
      - docker compose -f docker-compose.yml up --build -d
  
  stop:
    cmds:
      - docker compose -f docker-compose.yml down
