// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUserByEmail(ctx context.Context, email string) (int64, error)
	CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateTrain(ctx context.Context, arg CreateTrainParams) (Train, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeletePassenger(ctx context.Context, id int64) error
	DeletePayment(ctx context.Context, id pgtype.UUID) error
	DeleteReservation(ctx context.Context, id pgtype.UUID) error
	DeleteRoute(ctx context.Context, id int64) error
	DeleteSchedule(ctx context.Context, id int64) error
	DeleteTrain(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetPassenger(ctx context.Context, id int64) (Passenger, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error)
	GetRoute(ctx context.Context, id int64) (Route, error)
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	GetTrain(ctx context.Context, id int64) (Train, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListPassengers(ctx context.Context) ([]Passenger, error)
	ListPayments(ctx context.Context) ([]Payment, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error)
	ListRoute(ctx context.Context) ([]Route, error)
	ListSchedules(ctx context.Context) ([]Train, error)
	ListTrains(ctx context.Context) ([]Train, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePassenger(ctx context.Context, arg UpdatePassengerParams) error
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdateReservation(ctx context.Context, arg UpdateReservationParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) error
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error
	UpdateTrain(ctx context.Context, arg UpdateTrainParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
