// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schedules.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
   train_id, class_type, departure_date, available_seats, price, route_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, train_id, class_type, departure_date, arrival_date, available_seats, price, route_id, created_at, updated_at
`

type CreateScheduleParams struct {
	TrainID        int32            `db:"train_id" json:"train_id"`
	ClassType      TipeClass        `db:"class_type" json:"class_type"`
	DepartureDate  pgtype.Timestamp `db:"departure_date" json:"departure_date"`
	AvailableSeats int32            `db:"available_seats" json:"available_seats"`
	Price          int64            `db:"price" json:"price"`
	RouteID        int32            `db:"route_id" json:"route_id"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.TrainID,
		arg.ClassType,
		arg.DepartureDate,
		arg.AvailableSeats,
		arg.Price,
		arg.RouteID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.TrainID,
		&i.ClassType,
		&i.DepartureDate,
		&i.ArrivalDate,
		&i.AvailableSeats,
		&i.Price,
		&i.RouteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, train_id, class_type, departure_date, arrival_date, available_seats, price, route_id, created_at, updated_at FROM  schedules
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.TrainID,
		&i.ClassType,
		&i.DepartureDate,
		&i.ArrivalDate,
		&i.AvailableSeats,
		&i.Price,
		&i.RouteID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, name, capacity, created_at, updated_at FROM trains
ORDER BY name
`

func (q *Queries) ListSchedules(ctx context.Context) ([]Train, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Train{}
	for rows.Next() {
		var i Train
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE schedules
  set train_id = $2,
  class_type = $3,
  departure_date = $4,
  available_seats= $5,
  price = $6,
  route_id = $7
WHERE id = $1
`

type UpdateScheduleParams struct {
	ID             int64            `db:"id" json:"id"`
	TrainID        int32            `db:"train_id" json:"train_id"`
	ClassType      TipeClass        `db:"class_type" json:"class_type"`
	DepartureDate  pgtype.Timestamp `db:"departure_date" json:"departure_date"`
	AvailableSeats int32            `db:"available_seats" json:"available_seats"`
	Price          int64            `db:"price" json:"price"`
	RouteID        int32            `db:"route_id" json:"route_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.ID,
		arg.TrainID,
		arg.ClassType,
		arg.DepartureDate,
		arg.AvailableSeats,
		arg.Price,
		arg.RouteID,
	)
	return err
}
