DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS trains;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS payments;

